name: Build and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: 55 2 1 * *

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version
        id: vars
        run: |
          echo "::set-output name=version::$(date +'%Y.%m')"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-curl-loop:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-curl-loop:${{ steps.vars.outputs.version }}
          push: true